Repository jenkins-x/jenkins-x-builders-base, pull requests merged in 2019-09, with the labels that each got.

#52 feat: adding goreleaser to all builders
  changelog.sh
  docs/dev/changelog-footer.md
  docs/dev/changelog-header.md
  jenkins-x.yml
Labels: approved, size/S

#51 chore(deps): bump helm from v2.14.1 to v2.14.3
  Dockerfile.common
Labels: approved, size/XS

#50 chore(deps): bump skaffold from v0.31.0 to v0.37.0
  Dockerfile.common
Labels: approved, size/XS

#53 fix: remove old fork of helm3
  builder-base/Dockerfile.common
Labels: approved, lgtm, size/XS

#54 chore(deps): bump helm3 from v3.0.0-beta.2 to helm-v3.0.0-beta.3
  builder-base/Dockerfile.common
Labels: approved, size/XS

#55 fix: add velero binary
  Dockerfile.common
  builder-base/Dockerfile.common
Labels: approved, lgtm, size/S

#57 fix: downstream builds are now using 'jx step create pr'
  Dockerfile.common
  builder-base/Dockerfile.common
  jenkins-x.yml
  update-bot.sh
Labels: approved, size/M

#58 feat: add gcloud alpha commands needed for arcalos
  builder-base/Dockerfile.common
Labels: approved, size/XS

#62 chore: Cut down layers, switch to two PR calls, add builders-ml to that
  builder-base/Dockerfile.common
  update-bot.sh
Labels: approved, lgtm, size/L

#65 feat: add eksctl to the base image
  Dockerfile.common
  builder-base/Dockerfile.common
Labels: approved, lgtm, size/XS

#60 chore(deps): bump skaffold to v0.38.0
  Dockerfile.common
Labels: approved, lgtm, ok-to-test, size/XS

#64 fix: Unbreak updatebot
  jenkins-x.yml
  update-bot.sh
Labels: approved, size/S
