Repository jenkins-x/jenkins-x-builders-base, pull requests merged in 2019-11, with the labels that each got.

#70 chore(deps): bump gcloud from 265.0.0 to 270.0.0
  Dockerfile.common
Labels: size/XS, updatebot

#71 chore(deps): bump skaffold from 0.38.0 to 1.0.0
  Dockerfile.common
Labels: size/XS, updatebot

#72 fix: upgrade to latest helm3
  builder-base/Dockerfile.common
Labels: size/XS

#74 chore(deps): bump skaffold from 1.0.0 to 1.0.1
  Dockerfile.common
Labels: approved, lgtm, size/XS
