Repository jenkins-x/jenkins-x-builders-base, pull requests merged in 2019-03, with the labels that each got.

#1 feat: pushing ruby/swift images to the correct location
  jenkins-x.yml
  update-bot.sh
Labels: size/S

#2 fix: made updatebot script executable
  Dockerfile.common
  update-bot.sh
Labels: size/XS

#3 manually bump updatebot release as new builder image needed to automate this in future
  Dockerfile.common
Labels: approved, size/XS

#4 chore: reduced the number of downstream repositories
  .gitignore
  .updatebot.yml
Labels: approved, size/XS

#5 feat: added dummy dockerfile so updatebot can trigger
  Dockerfile
Labels: approved, size/XS

#6 chore: updating skaffold to 0.25.0
  Dockerfile.common
Labels: approved, size/XS

#7 feat: using single updatebot statement for downstream builds
  update-bot.sh
Labels: approved, size/S

#13 fix: stop variable expansion for updatebot command
  update-bot.sh
Labels: approved, size/S

#14 Updating helm to 2.13.1
  Dockerfile.common
Labels: approved, size/XS

#16 Updating gcloud to 239.0.0
  Dockerfile.common
Labels: approved, size/XS

#15 Updating skaffold to 0.26.0
  Dockerfile.common
Labels: approved, size/XS
